version: "3.0"
services:    
  cosmicapi:
    image: cosmicapi
    container_name: cosmicapi_container
    command: npm run serv -p 6906
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 6909:6906
    restart: unless-stopped

